name: Build XNNPack iOS static framework
on: [push, pull_request]
env:
  DEVELOPER_DIR: /Applications/Xcode_12.4.app/Contents/Developer

jobs:
  build-ios:
    runs-on: macos-10.15
    steps:
    - uses: actions/checkout@v2
      with:
        submodules: recursive

    - name: Build Release
      run: |
        scripts/build-ios-fat64.sh out
        zip --symlinks -r XNNPack_ios_framework.zip out/product
        zip --symlinks -r XNNPack_ios_build_data.zip out

    - uses: actions/upload-artifact@v2
      with:
        name: ios_framework
        path: XNNPack_ios_framework.zip
    - uses: actions/upload-artifact@v2
      with:
        name: ios_build_data
        path: XNNPack_ios_build_data.zip

